/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as BusinessChatRouteImport } from './routes/business.chat'
import { Route as BusinessDashboardRouteImport } from './routes/business.dashboard'
import { Route as BusinessRegisterRouteImport } from './routes/business.register'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as BusinessDashboardIndexRouteImport } from './routes/business.dashboard.index'
import { Route as BusinessDashboardBillingRouteImport } from './routes/business.dashboard.billing'
import { Route as BusinessDashboardBookingsRouteImport } from './routes/business.dashboard.bookings'
import { Route as BusinessDashboardBranchesRouteImport } from './routes/business.dashboard.branches'
import { Route as BusinessDashboardCalendarRouteImport } from './routes/business.dashboard.calendar'
import { Route as BusinessDashboardChatRouteImport } from './routes/business.dashboard.chat'
import { Route as BusinessDashboardCustomersRouteImport } from './routes/business.dashboard.customers'
import { Route as BusinessDashboardEmployeeScheduleRouteImport } from './routes/business.dashboard.employee-schedule'
import { Route as BusinessDashboardEmployeesRouteImport } from './routes/business.dashboard.employees'
import { Route as BusinessDashboardFinanceRouteImport } from './routes/business.dashboard.finance'
import { Route as BusinessDashboardNotificationsRouteImport } from './routes/business.dashboard.notifications'
import { Route as BusinessDashboardOrgProfileRouteImport } from './routes/business.dashboard.org-profile'
import { Route as BusinessDashboardPerformanceRouteImport } from './routes/business.dashboard.performance'
import { Route as BusinessDashboardProfileRouteImport } from './routes/business.dashboard.profile'
import { Route as BusinessDashboardQrPromotionRouteImport } from './routes/business.dashboard.qr-promotion'
import { Route as BusinessDashboardReportsRouteImport } from './routes/business.dashboard.reports'
import { Route as BusinessDashboardScheduleRouteImport } from './routes/business.dashboard.schedule'
import { Route as BusinessDashboardServicesRouteImport } from './routes/business.dashboard.services'
import { Route as BusinessDashboardSettingsRouteImport } from './routes/business.dashboard.settings'
import { Route as BusinessDashboardTodayClientsRouteImport } from './routes/business.dashboard.today-clients'
import { Route as BusinessDashboardBranchesIndexRouteImport } from './routes/business.dashboard.branches.index'
import { Route as BusinessDashboardBranchesBranchIdRouteImport } from './routes/business.dashboard.branches.$branchId'
import { Route as BusinessDashboardEmployeesIndexRouteImport } from './routes/business.dashboard.employees.index'
import { Route as BusinessDashboardEmployeesEmployeeIdRouteImport } from './routes/business.dashboard.employees.$employeeId'
import { Route as BusinessDashboardGovernmentModuleRouteImport } from './routes/business.dashboard.government.$module'
import { Route as BusinessDashboardTicketOrganizationIdRouteImport } from './routes/business.dashboard.ticket.$organizationId'
import { Route as BusinessDashboardTicketOrganizationIdIndexRouteImport } from './routes/business.dashboard.ticket.$organizationId.index'
import { Route as BusinessDashboardTicketOrganizationIdDashboardRouteImport } from './routes/business.dashboard.ticket.$organizationId.dashboard'
import { Route as BusinessDashboardTicketOrganizationIdEventsRouteImport } from './routes/business.dashboard.ticket.$organizationId.events'
import { Route as BusinessDashboardTicketOrganizationIdGatesRouteImport } from './routes/business.dashboard.ticket.$organizationId.gates'
import { Route as BusinessDashboardTicketOrganizationIdHelpRouteImport } from './routes/business.dashboard.ticket.$organizationId.help'
import { Route as BusinessDashboardTicketOrganizationIdOrdersRouteImport } from './routes/business.dashboard.ticket.$organizationId.orders'
import { Route as BusinessDashboardTicketOrganizationIdReportsRouteImport } from './routes/business.dashboard.ticket.$organizationId.reports'
import { Route as BusinessDashboardTicketOrganizationIdScannerRouteImport } from './routes/business.dashboard.ticket.$organizationId.scanner'
import { Route as BusinessDashboardTicketOrganizationIdSchedulesRouteImport } from './routes/business.dashboard.ticket.$organizationId.schedules'
import { Route as BusinessDashboardTicketOrganizationIdSettingsRouteImport } from './routes/business.dashboard.ticket.$organizationId.settings'
import { Route as BusinessDashboardTicketOrganizationIdTicketTypesRouteImport } from './routes/business.dashboard.ticket.$organizationId.ticket-types'
import { Route as BusinessDashboardTicketOrganizationIdVenuesRouteImport } from './routes/business.dashboard.ticket.$organizationId.venues'
import { Route as BusinessDashboardTicketOrganizationIdEventsIndexRouteImport } from './routes/business.dashboard.ticket.$organizationId.events.index'
import { Route as BusinessDashboardTicketOrganizationIdEventsEventIdRouteImport } from './routes/business.dashboard.ticket.$organizationId.events.$eventId'
import { Route as BusinessDashboardTicketOrganizationIdEventsNewRouteImport } from './routes/business.dashboard.ticket.$organizationId.events.new'
import { Route as BusinessDashboardTicketOrganizationIdHallsHallIdRouteImport } from './routes/business.dashboard.ticket.$organizationId.halls.$hallId'
import { Route as BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRouteImport } from './routes/business.dashboard.ticket.$organizationId.seat-maps.$layoutId'
import { Route as BusinessDashboardTicketOrganizationIdVenuesIndexRouteImport } from './routes/business.dashboard.ticket.$organizationId.venues.index'
import { Route as BusinessDashboardTicketOrganizationIdVenuesVenueIdRouteImport } from './routes/business.dashboard.ticket.$organizationId.venues.$venueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessChatRoute = BusinessChatRouteImport.update({
  id: '/business/chat',
  path: '/business/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardRoute = BusinessDashboardRouteImport.update({
  id: '/business/dashboard',
  path: '/business/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegisterRoute = BusinessRegisterRouteImport.update({
  id: '/business/register',
  path: '/business/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessDashboardIndexRoute = BusinessDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const BusinessDashboardBillingRoute =
  BusinessDashboardBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBookingsRoute =
  BusinessDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBranchesRoute =
  BusinessDashboardBranchesRouteImport.update({
    id: '/branches',
    path: '/branches',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardCalendarRoute =
  BusinessDashboardCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardChatRoute = BusinessDashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BusinessDashboardRoute,
} as any)
const BusinessDashboardCustomersRoute =
  BusinessDashboardCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardEmployeeScheduleRoute =
  BusinessDashboardEmployeeScheduleRouteImport.update({
    id: '/employee-schedule',
    path: '/employee-schedule',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardEmployeesRoute =
  BusinessDashboardEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardFinanceRoute =
  BusinessDashboardFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardNotificationsRoute =
  BusinessDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardOrgProfileRoute =
  BusinessDashboardOrgProfileRouteImport.update({
    id: '/org-profile',
    path: '/org-profile',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardPerformanceRoute =
  BusinessDashboardPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardProfileRoute =
  BusinessDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardQrPromotionRoute =
  BusinessDashboardQrPromotionRouteImport.update({
    id: '/qr-promotion',
    path: '/qr-promotion',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardReportsRoute =
  BusinessDashboardReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardScheduleRoute =
  BusinessDashboardScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardServicesRoute =
  BusinessDashboardServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardSettingsRoute =
  BusinessDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardTodayClientsRoute =
  BusinessDashboardTodayClientsRouteImport.update({
    id: '/today-clients',
    path: '/today-clients',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardBranchesIndexRoute =
  BusinessDashboardBranchesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessDashboardBranchesRoute,
  } as any)
const BusinessDashboardBranchesBranchIdRoute =
  BusinessDashboardBranchesBranchIdRouteImport.update({
    id: '/$branchId',
    path: '/$branchId',
    getParentRoute: () => BusinessDashboardBranchesRoute,
  } as any)
const BusinessDashboardEmployeesIndexRoute =
  BusinessDashboardEmployeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessDashboardEmployeesRoute,
  } as any)
const BusinessDashboardEmployeesEmployeeIdRoute =
  BusinessDashboardEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => BusinessDashboardEmployeesRoute,
  } as any)
const BusinessDashboardGovernmentModuleRoute =
  BusinessDashboardGovernmentModuleRouteImport.update({
    id: '/government/$module',
    path: '/government/$module',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdRoute =
  BusinessDashboardTicketOrganizationIdRouteImport.update({
    id: '/ticket/$organizationId',
    path: '/ticket/$organizationId',
    getParentRoute: () => BusinessDashboardRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdIndexRoute =
  BusinessDashboardTicketOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdDashboardRoute =
  BusinessDashboardTicketOrganizationIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdEventsRoute =
  BusinessDashboardTicketOrganizationIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdGatesRoute =
  BusinessDashboardTicketOrganizationIdGatesRouteImport.update({
    id: '/gates',
    path: '/gates',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdHelpRoute =
  BusinessDashboardTicketOrganizationIdHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdOrdersRoute =
  BusinessDashboardTicketOrganizationIdOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdReportsRoute =
  BusinessDashboardTicketOrganizationIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdScannerRoute =
  BusinessDashboardTicketOrganizationIdScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdSchedulesRoute =
  BusinessDashboardTicketOrganizationIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdSettingsRoute =
  BusinessDashboardTicketOrganizationIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdTicketTypesRoute =
  BusinessDashboardTicketOrganizationIdTicketTypesRouteImport.update({
    id: '/ticket-types',
    path: '/ticket-types',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdVenuesRoute =
  BusinessDashboardTicketOrganizationIdVenuesRouteImport.update({
    id: '/venues',
    path: '/venues',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdEventsIndexRoute =
  BusinessDashboardTicketOrganizationIdEventsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdEventsRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdEventsEventIdRoute =
  BusinessDashboardTicketOrganizationIdEventsEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdEventsRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdEventsNewRoute =
  BusinessDashboardTicketOrganizationIdEventsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdEventsRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdHallsHallIdRoute =
  BusinessDashboardTicketOrganizationIdHallsHallIdRouteImport.update({
    id: '/halls/$hallId',
    path: '/halls/$hallId',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute =
  BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRouteImport.update({
    id: '/seat-maps/$layoutId',
    path: '/seat-maps/$layoutId',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdVenuesIndexRoute =
  BusinessDashboardTicketOrganizationIdVenuesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdVenuesRoute,
  } as any)
const BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute =
  BusinessDashboardTicketOrganizationIdVenuesVenueIdRouteImport.update({
    id: '/$venueId',
    path: '/$venueId',
    getParentRoute: () => BusinessDashboardTicketOrganizationIdVenuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/business/chat': typeof BusinessChatRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/business/register': typeof BusinessRegisterRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/business/dashboard/billing': typeof BusinessDashboardBillingRoute
  '/business/dashboard/bookings': typeof BusinessDashboardBookingsRoute
  '/business/dashboard/branches': typeof BusinessDashboardBranchesRouteWithChildren
  '/business/dashboard/calendar': typeof BusinessDashboardCalendarRoute
  '/business/dashboard/chat': typeof BusinessDashboardChatRoute
  '/business/dashboard/customers': typeof BusinessDashboardCustomersRoute
  '/business/dashboard/employee-schedule': typeof BusinessDashboardEmployeeScheduleRoute
  '/business/dashboard/employees': typeof BusinessDashboardEmployeesRouteWithChildren
  '/business/dashboard/finance': typeof BusinessDashboardFinanceRoute
  '/business/dashboard/notifications': typeof BusinessDashboardNotificationsRoute
  '/business/dashboard/org-profile': typeof BusinessDashboardOrgProfileRoute
  '/business/dashboard/performance': typeof BusinessDashboardPerformanceRoute
  '/business/dashboard/profile': typeof BusinessDashboardProfileRoute
  '/business/dashboard/qr-promotion': typeof BusinessDashboardQrPromotionRoute
  '/business/dashboard/reports': typeof BusinessDashboardReportsRoute
  '/business/dashboard/schedule': typeof BusinessDashboardScheduleRoute
  '/business/dashboard/services': typeof BusinessDashboardServicesRoute
  '/business/dashboard/settings': typeof BusinessDashboardSettingsRoute
  '/business/dashboard/today-clients': typeof BusinessDashboardTodayClientsRoute
  '/business/dashboard/': typeof BusinessDashboardIndexRoute
  '/business/dashboard/branches/$branchId': typeof BusinessDashboardBranchesBranchIdRoute
  '/business/dashboard/employees/$employeeId': typeof BusinessDashboardEmployeesEmployeeIdRoute
  '/business/dashboard/government/$module': typeof BusinessDashboardGovernmentModuleRoute
  '/business/dashboard/ticket/$organizationId': typeof BusinessDashboardTicketOrganizationIdRouteWithChildren
  '/business/dashboard/branches/': typeof BusinessDashboardBranchesIndexRoute
  '/business/dashboard/employees/': typeof BusinessDashboardEmployeesIndexRoute
  '/business/dashboard/ticket/$organizationId/dashboard': typeof BusinessDashboardTicketOrganizationIdDashboardRoute
  '/business/dashboard/ticket/$organizationId/events': typeof BusinessDashboardTicketOrganizationIdEventsRouteWithChildren
  '/business/dashboard/ticket/$organizationId/gates': typeof BusinessDashboardTicketOrganizationIdGatesRoute
  '/business/dashboard/ticket/$organizationId/help': typeof BusinessDashboardTicketOrganizationIdHelpRoute
  '/business/dashboard/ticket/$organizationId/orders': typeof BusinessDashboardTicketOrganizationIdOrdersRoute
  '/business/dashboard/ticket/$organizationId/reports': typeof BusinessDashboardTicketOrganizationIdReportsRoute
  '/business/dashboard/ticket/$organizationId/scanner': typeof BusinessDashboardTicketOrganizationIdScannerRoute
  '/business/dashboard/ticket/$organizationId/schedules': typeof BusinessDashboardTicketOrganizationIdSchedulesRoute
  '/business/dashboard/ticket/$organizationId/settings': typeof BusinessDashboardTicketOrganizationIdSettingsRoute
  '/business/dashboard/ticket/$organizationId/ticket-types': typeof BusinessDashboardTicketOrganizationIdTicketTypesRoute
  '/business/dashboard/ticket/$organizationId/venues': typeof BusinessDashboardTicketOrganizationIdVenuesRouteWithChildren
  '/business/dashboard/ticket/$organizationId/': typeof BusinessDashboardTicketOrganizationIdIndexRoute
  '/business/dashboard/ticket/$organizationId/events/$eventId': typeof BusinessDashboardTicketOrganizationIdEventsEventIdRoute
  '/business/dashboard/ticket/$organizationId/events/new': typeof BusinessDashboardTicketOrganizationIdEventsNewRoute
  '/business/dashboard/ticket/$organizationId/halls/$hallId': typeof BusinessDashboardTicketOrganizationIdHallsHallIdRoute
  '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId': typeof BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute
  '/business/dashboard/ticket/$organizationId/venues/$venueId': typeof BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute
  '/business/dashboard/ticket/$organizationId/events/': typeof BusinessDashboardTicketOrganizationIdEventsIndexRoute
  '/business/dashboard/ticket/$organizationId/venues/': typeof BusinessDashboardTicketOrganizationIdVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/business/chat': typeof BusinessChatRoute
  '/business/register': typeof BusinessRegisterRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/business/dashboard/billing': typeof BusinessDashboardBillingRoute
  '/business/dashboard/bookings': typeof BusinessDashboardBookingsRoute
  '/business/dashboard/calendar': typeof BusinessDashboardCalendarRoute
  '/business/dashboard/chat': typeof BusinessDashboardChatRoute
  '/business/dashboard/customers': typeof BusinessDashboardCustomersRoute
  '/business/dashboard/employee-schedule': typeof BusinessDashboardEmployeeScheduleRoute
  '/business/dashboard/finance': typeof BusinessDashboardFinanceRoute
  '/business/dashboard/notifications': typeof BusinessDashboardNotificationsRoute
  '/business/dashboard/org-profile': typeof BusinessDashboardOrgProfileRoute
  '/business/dashboard/performance': typeof BusinessDashboardPerformanceRoute
  '/business/dashboard/profile': typeof BusinessDashboardProfileRoute
  '/business/dashboard/qr-promotion': typeof BusinessDashboardQrPromotionRoute
  '/business/dashboard/reports': typeof BusinessDashboardReportsRoute
  '/business/dashboard/schedule': typeof BusinessDashboardScheduleRoute
  '/business/dashboard/services': typeof BusinessDashboardServicesRoute
  '/business/dashboard/settings': typeof BusinessDashboardSettingsRoute
  '/business/dashboard/today-clients': typeof BusinessDashboardTodayClientsRoute
  '/business/dashboard': typeof BusinessDashboardIndexRoute
  '/business/dashboard/branches/$branchId': typeof BusinessDashboardBranchesBranchIdRoute
  '/business/dashboard/employees/$employeeId': typeof BusinessDashboardEmployeesEmployeeIdRoute
  '/business/dashboard/government/$module': typeof BusinessDashboardGovernmentModuleRoute
  '/business/dashboard/branches': typeof BusinessDashboardBranchesIndexRoute
  '/business/dashboard/employees': typeof BusinessDashboardEmployeesIndexRoute
  '/business/dashboard/ticket/$organizationId/dashboard': typeof BusinessDashboardTicketOrganizationIdDashboardRoute
  '/business/dashboard/ticket/$organizationId/gates': typeof BusinessDashboardTicketOrganizationIdGatesRoute
  '/business/dashboard/ticket/$organizationId/help': typeof BusinessDashboardTicketOrganizationIdHelpRoute
  '/business/dashboard/ticket/$organizationId/orders': typeof BusinessDashboardTicketOrganizationIdOrdersRoute
  '/business/dashboard/ticket/$organizationId/reports': typeof BusinessDashboardTicketOrganizationIdReportsRoute
  '/business/dashboard/ticket/$organizationId/scanner': typeof BusinessDashboardTicketOrganizationIdScannerRoute
  '/business/dashboard/ticket/$organizationId/schedules': typeof BusinessDashboardTicketOrganizationIdSchedulesRoute
  '/business/dashboard/ticket/$organizationId/settings': typeof BusinessDashboardTicketOrganizationIdSettingsRoute
  '/business/dashboard/ticket/$organizationId/ticket-types': typeof BusinessDashboardTicketOrganizationIdTicketTypesRoute
  '/business/dashboard/ticket/$organizationId': typeof BusinessDashboardTicketOrganizationIdIndexRoute
  '/business/dashboard/ticket/$organizationId/events/$eventId': typeof BusinessDashboardTicketOrganizationIdEventsEventIdRoute
  '/business/dashboard/ticket/$organizationId/events/new': typeof BusinessDashboardTicketOrganizationIdEventsNewRoute
  '/business/dashboard/ticket/$organizationId/halls/$hallId': typeof BusinessDashboardTicketOrganizationIdHallsHallIdRoute
  '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId': typeof BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute
  '/business/dashboard/ticket/$organizationId/venues/$venueId': typeof BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute
  '/business/dashboard/ticket/$organizationId/events': typeof BusinessDashboardTicketOrganizationIdEventsIndexRoute
  '/business/dashboard/ticket/$organizationId/venues': typeof BusinessDashboardTicketOrganizationIdVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/business/chat': typeof BusinessChatRoute
  '/business/dashboard': typeof BusinessDashboardRouteWithChildren
  '/business/register': typeof BusinessRegisterRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/business/dashboard/billing': typeof BusinessDashboardBillingRoute
  '/business/dashboard/bookings': typeof BusinessDashboardBookingsRoute
  '/business/dashboard/branches': typeof BusinessDashboardBranchesRouteWithChildren
  '/business/dashboard/calendar': typeof BusinessDashboardCalendarRoute
  '/business/dashboard/chat': typeof BusinessDashboardChatRoute
  '/business/dashboard/customers': typeof BusinessDashboardCustomersRoute
  '/business/dashboard/employee-schedule': typeof BusinessDashboardEmployeeScheduleRoute
  '/business/dashboard/employees': typeof BusinessDashboardEmployeesRouteWithChildren
  '/business/dashboard/finance': typeof BusinessDashboardFinanceRoute
  '/business/dashboard/notifications': typeof BusinessDashboardNotificationsRoute
  '/business/dashboard/org-profile': typeof BusinessDashboardOrgProfileRoute
  '/business/dashboard/performance': typeof BusinessDashboardPerformanceRoute
  '/business/dashboard/profile': typeof BusinessDashboardProfileRoute
  '/business/dashboard/qr-promotion': typeof BusinessDashboardQrPromotionRoute
  '/business/dashboard/reports': typeof BusinessDashboardReportsRoute
  '/business/dashboard/schedule': typeof BusinessDashboardScheduleRoute
  '/business/dashboard/services': typeof BusinessDashboardServicesRoute
  '/business/dashboard/settings': typeof BusinessDashboardSettingsRoute
  '/business/dashboard/today-clients': typeof BusinessDashboardTodayClientsRoute
  '/business/dashboard/': typeof BusinessDashboardIndexRoute
  '/business/dashboard/branches/$branchId': typeof BusinessDashboardBranchesBranchIdRoute
  '/business/dashboard/employees/$employeeId': typeof BusinessDashboardEmployeesEmployeeIdRoute
  '/business/dashboard/government/$module': typeof BusinessDashboardGovernmentModuleRoute
  '/business/dashboard/ticket/$organizationId': typeof BusinessDashboardTicketOrganizationIdRouteWithChildren
  '/business/dashboard/branches/': typeof BusinessDashboardBranchesIndexRoute
  '/business/dashboard/employees/': typeof BusinessDashboardEmployeesIndexRoute
  '/business/dashboard/ticket/$organizationId/dashboard': typeof BusinessDashboardTicketOrganizationIdDashboardRoute
  '/business/dashboard/ticket/$organizationId/events': typeof BusinessDashboardTicketOrganizationIdEventsRouteWithChildren
  '/business/dashboard/ticket/$organizationId/gates': typeof BusinessDashboardTicketOrganizationIdGatesRoute
  '/business/dashboard/ticket/$organizationId/help': typeof BusinessDashboardTicketOrganizationIdHelpRoute
  '/business/dashboard/ticket/$organizationId/orders': typeof BusinessDashboardTicketOrganizationIdOrdersRoute
  '/business/dashboard/ticket/$organizationId/reports': typeof BusinessDashboardTicketOrganizationIdReportsRoute
  '/business/dashboard/ticket/$organizationId/scanner': typeof BusinessDashboardTicketOrganizationIdScannerRoute
  '/business/dashboard/ticket/$organizationId/schedules': typeof BusinessDashboardTicketOrganizationIdSchedulesRoute
  '/business/dashboard/ticket/$organizationId/settings': typeof BusinessDashboardTicketOrganizationIdSettingsRoute
  '/business/dashboard/ticket/$organizationId/ticket-types': typeof BusinessDashboardTicketOrganizationIdTicketTypesRoute
  '/business/dashboard/ticket/$organizationId/venues': typeof BusinessDashboardTicketOrganizationIdVenuesRouteWithChildren
  '/business/dashboard/ticket/$organizationId/': typeof BusinessDashboardTicketOrganizationIdIndexRoute
  '/business/dashboard/ticket/$organizationId/events/$eventId': typeof BusinessDashboardTicketOrganizationIdEventsEventIdRoute
  '/business/dashboard/ticket/$organizationId/events/new': typeof BusinessDashboardTicketOrganizationIdEventsNewRoute
  '/business/dashboard/ticket/$organizationId/halls/$hallId': typeof BusinessDashboardTicketOrganizationIdHallsHallIdRoute
  '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId': typeof BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute
  '/business/dashboard/ticket/$organizationId/venues/$venueId': typeof BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute
  '/business/dashboard/ticket/$organizationId/events/': typeof BusinessDashboardTicketOrganizationIdEventsIndexRoute
  '/business/dashboard/ticket/$organizationId/venues/': typeof BusinessDashboardTicketOrganizationIdVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/business/chat'
    | '/business/dashboard'
    | '/business/register'
    | '/event/$eventId'
    | '/business/dashboard/billing'
    | '/business/dashboard/bookings'
    | '/business/dashboard/branches'
    | '/business/dashboard/calendar'
    | '/business/dashboard/chat'
    | '/business/dashboard/customers'
    | '/business/dashboard/employee-schedule'
    | '/business/dashboard/employees'
    | '/business/dashboard/finance'
    | '/business/dashboard/notifications'
    | '/business/dashboard/org-profile'
    | '/business/dashboard/performance'
    | '/business/dashboard/profile'
    | '/business/dashboard/qr-promotion'
    | '/business/dashboard/reports'
    | '/business/dashboard/schedule'
    | '/business/dashboard/services'
    | '/business/dashboard/settings'
    | '/business/dashboard/today-clients'
    | '/business/dashboard/'
    | '/business/dashboard/branches/$branchId'
    | '/business/dashboard/employees/$employeeId'
    | '/business/dashboard/government/$module'
    | '/business/dashboard/ticket/$organizationId'
    | '/business/dashboard/branches/'
    | '/business/dashboard/employees/'
    | '/business/dashboard/ticket/$organizationId/dashboard'
    | '/business/dashboard/ticket/$organizationId/events'
    | '/business/dashboard/ticket/$organizationId/gates'
    | '/business/dashboard/ticket/$organizationId/help'
    | '/business/dashboard/ticket/$organizationId/orders'
    | '/business/dashboard/ticket/$organizationId/reports'
    | '/business/dashboard/ticket/$organizationId/scanner'
    | '/business/dashboard/ticket/$organizationId/schedules'
    | '/business/dashboard/ticket/$organizationId/settings'
    | '/business/dashboard/ticket/$organizationId/ticket-types'
    | '/business/dashboard/ticket/$organizationId/venues'
    | '/business/dashboard/ticket/$organizationId/'
    | '/business/dashboard/ticket/$organizationId/events/$eventId'
    | '/business/dashboard/ticket/$organizationId/events/new'
    | '/business/dashboard/ticket/$organizationId/halls/$hallId'
    | '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId'
    | '/business/dashboard/ticket/$organizationId/venues/$venueId'
    | '/business/dashboard/ticket/$organizationId/events/'
    | '/business/dashboard/ticket/$organizationId/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/business/chat'
    | '/business/register'
    | '/event/$eventId'
    | '/business/dashboard/billing'
    | '/business/dashboard/bookings'
    | '/business/dashboard/calendar'
    | '/business/dashboard/chat'
    | '/business/dashboard/customers'
    | '/business/dashboard/employee-schedule'
    | '/business/dashboard/finance'
    | '/business/dashboard/notifications'
    | '/business/dashboard/org-profile'
    | '/business/dashboard/performance'
    | '/business/dashboard/profile'
    | '/business/dashboard/qr-promotion'
    | '/business/dashboard/reports'
    | '/business/dashboard/schedule'
    | '/business/dashboard/services'
    | '/business/dashboard/settings'
    | '/business/dashboard/today-clients'
    | '/business/dashboard'
    | '/business/dashboard/branches/$branchId'
    | '/business/dashboard/employees/$employeeId'
    | '/business/dashboard/government/$module'
    | '/business/dashboard/branches'
    | '/business/dashboard/employees'
    | '/business/dashboard/ticket/$organizationId/dashboard'
    | '/business/dashboard/ticket/$organizationId/gates'
    | '/business/dashboard/ticket/$organizationId/help'
    | '/business/dashboard/ticket/$organizationId/orders'
    | '/business/dashboard/ticket/$organizationId/reports'
    | '/business/dashboard/ticket/$organizationId/scanner'
    | '/business/dashboard/ticket/$organizationId/schedules'
    | '/business/dashboard/ticket/$organizationId/settings'
    | '/business/dashboard/ticket/$organizationId/ticket-types'
    | '/business/dashboard/ticket/$organizationId'
    | '/business/dashboard/ticket/$organizationId/events/$eventId'
    | '/business/dashboard/ticket/$organizationId/events/new'
    | '/business/dashboard/ticket/$organizationId/halls/$hallId'
    | '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId'
    | '/business/dashboard/ticket/$organizationId/venues/$venueId'
    | '/business/dashboard/ticket/$organizationId/events'
    | '/business/dashboard/ticket/$organizationId/venues'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/business/chat'
    | '/business/dashboard'
    | '/business/register'
    | '/event/$eventId'
    | '/business/dashboard/billing'
    | '/business/dashboard/bookings'
    | '/business/dashboard/branches'
    | '/business/dashboard/calendar'
    | '/business/dashboard/chat'
    | '/business/dashboard/customers'
    | '/business/dashboard/employee-schedule'
    | '/business/dashboard/employees'
    | '/business/dashboard/finance'
    | '/business/dashboard/notifications'
    | '/business/dashboard/org-profile'
    | '/business/dashboard/performance'
    | '/business/dashboard/profile'
    | '/business/dashboard/qr-promotion'
    | '/business/dashboard/reports'
    | '/business/dashboard/schedule'
    | '/business/dashboard/services'
    | '/business/dashboard/settings'
    | '/business/dashboard/today-clients'
    | '/business/dashboard/'
    | '/business/dashboard/branches/$branchId'
    | '/business/dashboard/employees/$employeeId'
    | '/business/dashboard/government/$module'
    | '/business/dashboard/ticket/$organizationId'
    | '/business/dashboard/branches/'
    | '/business/dashboard/employees/'
    | '/business/dashboard/ticket/$organizationId/dashboard'
    | '/business/dashboard/ticket/$organizationId/events'
    | '/business/dashboard/ticket/$organizationId/gates'
    | '/business/dashboard/ticket/$organizationId/help'
    | '/business/dashboard/ticket/$organizationId/orders'
    | '/business/dashboard/ticket/$organizationId/reports'
    | '/business/dashboard/ticket/$organizationId/scanner'
    | '/business/dashboard/ticket/$organizationId/schedules'
    | '/business/dashboard/ticket/$organizationId/settings'
    | '/business/dashboard/ticket/$organizationId/ticket-types'
    | '/business/dashboard/ticket/$organizationId/venues'
    | '/business/dashboard/ticket/$organizationId/'
    | '/business/dashboard/ticket/$organizationId/events/$eventId'
    | '/business/dashboard/ticket/$organizationId/events/new'
    | '/business/dashboard/ticket/$organizationId/halls/$hallId'
    | '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId'
    | '/business/dashboard/ticket/$organizationId/venues/$venueId'
    | '/business/dashboard/ticket/$organizationId/events/'
    | '/business/dashboard/ticket/$organizationId/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  BusinessChatRoute: typeof BusinessChatRoute
  BusinessDashboardRoute: typeof BusinessDashboardRouteWithChildren
  BusinessRegisterRoute: typeof BusinessRegisterRoute
  EventEventIdRoute: typeof EventEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/chat': {
      id: '/business/chat'
      path: '/business/chat'
      fullPath: '/business/chat'
      preLoaderRoute: typeof BusinessChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard': {
      id: '/business/dashboard'
      path: '/business/dashboard'
      fullPath: '/business/dashboard'
      preLoaderRoute: typeof BusinessDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/register': {
      id: '/business/register'
      path: '/business/register'
      fullPath: '/business/register'
      preLoaderRoute: typeof BusinessRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/dashboard/': {
      id: '/business/dashboard/'
      path: '/'
      fullPath: '/business/dashboard/'
      preLoaderRoute: typeof BusinessDashboardIndexRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/billing': {
      id: '/business/dashboard/billing'
      path: '/billing'
      fullPath: '/business/dashboard/billing'
      preLoaderRoute: typeof BusinessDashboardBillingRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/bookings': {
      id: '/business/dashboard/bookings'
      path: '/bookings'
      fullPath: '/business/dashboard/bookings'
      preLoaderRoute: typeof BusinessDashboardBookingsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/branches': {
      id: '/business/dashboard/branches'
      path: '/branches'
      fullPath: '/business/dashboard/branches'
      preLoaderRoute: typeof BusinessDashboardBranchesRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/calendar': {
      id: '/business/dashboard/calendar'
      path: '/calendar'
      fullPath: '/business/dashboard/calendar'
      preLoaderRoute: typeof BusinessDashboardCalendarRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/chat': {
      id: '/business/dashboard/chat'
      path: '/chat'
      fullPath: '/business/dashboard/chat'
      preLoaderRoute: typeof BusinessDashboardChatRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/customers': {
      id: '/business/dashboard/customers'
      path: '/customers'
      fullPath: '/business/dashboard/customers'
      preLoaderRoute: typeof BusinessDashboardCustomersRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/employee-schedule': {
      id: '/business/dashboard/employee-schedule'
      path: '/employee-schedule'
      fullPath: '/business/dashboard/employee-schedule'
      preLoaderRoute: typeof BusinessDashboardEmployeeScheduleRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/employees': {
      id: '/business/dashboard/employees'
      path: '/employees'
      fullPath: '/business/dashboard/employees'
      preLoaderRoute: typeof BusinessDashboardEmployeesRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/finance': {
      id: '/business/dashboard/finance'
      path: '/finance'
      fullPath: '/business/dashboard/finance'
      preLoaderRoute: typeof BusinessDashboardFinanceRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/notifications': {
      id: '/business/dashboard/notifications'
      path: '/notifications'
      fullPath: '/business/dashboard/notifications'
      preLoaderRoute: typeof BusinessDashboardNotificationsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/org-profile': {
      id: '/business/dashboard/org-profile'
      path: '/org-profile'
      fullPath: '/business/dashboard/org-profile'
      preLoaderRoute: typeof BusinessDashboardOrgProfileRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/performance': {
      id: '/business/dashboard/performance'
      path: '/performance'
      fullPath: '/business/dashboard/performance'
      preLoaderRoute: typeof BusinessDashboardPerformanceRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/profile': {
      id: '/business/dashboard/profile'
      path: '/profile'
      fullPath: '/business/dashboard/profile'
      preLoaderRoute: typeof BusinessDashboardProfileRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/qr-promotion': {
      id: '/business/dashboard/qr-promotion'
      path: '/qr-promotion'
      fullPath: '/business/dashboard/qr-promotion'
      preLoaderRoute: typeof BusinessDashboardQrPromotionRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/reports': {
      id: '/business/dashboard/reports'
      path: '/reports'
      fullPath: '/business/dashboard/reports'
      preLoaderRoute: typeof BusinessDashboardReportsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/schedule': {
      id: '/business/dashboard/schedule'
      path: '/schedule'
      fullPath: '/business/dashboard/schedule'
      preLoaderRoute: typeof BusinessDashboardScheduleRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/services': {
      id: '/business/dashboard/services'
      path: '/services'
      fullPath: '/business/dashboard/services'
      preLoaderRoute: typeof BusinessDashboardServicesRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/settings': {
      id: '/business/dashboard/settings'
      path: '/settings'
      fullPath: '/business/dashboard/settings'
      preLoaderRoute: typeof BusinessDashboardSettingsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/today-clients': {
      id: '/business/dashboard/today-clients'
      path: '/today-clients'
      fullPath: '/business/dashboard/today-clients'
      preLoaderRoute: typeof BusinessDashboardTodayClientsRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/branches/': {
      id: '/business/dashboard/branches/'
      path: '/'
      fullPath: '/business/dashboard/branches/'
      preLoaderRoute: typeof BusinessDashboardBranchesIndexRouteImport
      parentRoute: typeof BusinessDashboardBranchesRoute
    }
    '/business/dashboard/branches/$branchId': {
      id: '/business/dashboard/branches/$branchId'
      path: '/$branchId'
      fullPath: '/business/dashboard/branches/$branchId'
      preLoaderRoute: typeof BusinessDashboardBranchesBranchIdRouteImport
      parentRoute: typeof BusinessDashboardBranchesRoute
    }
    '/business/dashboard/employees/': {
      id: '/business/dashboard/employees/'
      path: '/'
      fullPath: '/business/dashboard/employees/'
      preLoaderRoute: typeof BusinessDashboardEmployeesIndexRouteImport
      parentRoute: typeof BusinessDashboardEmployeesRoute
    }
    '/business/dashboard/employees/$employeeId': {
      id: '/business/dashboard/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/business/dashboard/employees/$employeeId'
      preLoaderRoute: typeof BusinessDashboardEmployeesEmployeeIdRouteImport
      parentRoute: typeof BusinessDashboardEmployeesRoute
    }
    '/business/dashboard/government/$module': {
      id: '/business/dashboard/government/$module'
      path: '/government/$module'
      fullPath: '/business/dashboard/government/$module'
      preLoaderRoute: typeof BusinessDashboardGovernmentModuleRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/ticket/$organizationId': {
      id: '/business/dashboard/ticket/$organizationId'
      path: '/ticket/$organizationId'
      fullPath: '/business/dashboard/ticket/$organizationId'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdRouteImport
      parentRoute: typeof BusinessDashboardRoute
    }
    '/business/dashboard/ticket/$organizationId/': {
      id: '/business/dashboard/ticket/$organizationId/'
      path: '/'
      fullPath: '/business/dashboard/ticket/$organizationId/'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdIndexRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/dashboard': {
      id: '/business/dashboard/ticket/$organizationId/dashboard'
      path: '/dashboard'
      fullPath: '/business/dashboard/ticket/$organizationId/dashboard'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdDashboardRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/events': {
      id: '/business/dashboard/ticket/$organizationId/events'
      path: '/events'
      fullPath: '/business/dashboard/ticket/$organizationId/events'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdEventsRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/gates': {
      id: '/business/dashboard/ticket/$organizationId/gates'
      path: '/gates'
      fullPath: '/business/dashboard/ticket/$organizationId/gates'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdGatesRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/help': {
      id: '/business/dashboard/ticket/$organizationId/help'
      path: '/help'
      fullPath: '/business/dashboard/ticket/$organizationId/help'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdHelpRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/orders': {
      id: '/business/dashboard/ticket/$organizationId/orders'
      path: '/orders'
      fullPath: '/business/dashboard/ticket/$organizationId/orders'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdOrdersRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/reports': {
      id: '/business/dashboard/ticket/$organizationId/reports'
      path: '/reports'
      fullPath: '/business/dashboard/ticket/$organizationId/reports'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdReportsRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/scanner': {
      id: '/business/dashboard/ticket/$organizationId/scanner'
      path: '/scanner'
      fullPath: '/business/dashboard/ticket/$organizationId/scanner'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdScannerRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/schedules': {
      id: '/business/dashboard/ticket/$organizationId/schedules'
      path: '/schedules'
      fullPath: '/business/dashboard/ticket/$organizationId/schedules'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdSchedulesRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/settings': {
      id: '/business/dashboard/ticket/$organizationId/settings'
      path: '/settings'
      fullPath: '/business/dashboard/ticket/$organizationId/settings'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdSettingsRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/ticket-types': {
      id: '/business/dashboard/ticket/$organizationId/ticket-types'
      path: '/ticket-types'
      fullPath: '/business/dashboard/ticket/$organizationId/ticket-types'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdTicketTypesRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/venues': {
      id: '/business/dashboard/ticket/$organizationId/venues'
      path: '/venues'
      fullPath: '/business/dashboard/ticket/$organizationId/venues'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdVenuesRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/events/': {
      id: '/business/dashboard/ticket/$organizationId/events/'
      path: '/'
      fullPath: '/business/dashboard/ticket/$organizationId/events/'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdEventsIndexRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdEventsRoute
    }
    '/business/dashboard/ticket/$organizationId/events/$eventId': {
      id: '/business/dashboard/ticket/$organizationId/events/$eventId'
      path: '/$eventId'
      fullPath: '/business/dashboard/ticket/$organizationId/events/$eventId'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdEventsEventIdRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdEventsRoute
    }
    '/business/dashboard/ticket/$organizationId/events/new': {
      id: '/business/dashboard/ticket/$organizationId/events/new'
      path: '/new'
      fullPath: '/business/dashboard/ticket/$organizationId/events/new'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdEventsNewRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdEventsRoute
    }
    '/business/dashboard/ticket/$organizationId/halls/$hallId': {
      id: '/business/dashboard/ticket/$organizationId/halls/$hallId'
      path: '/halls/$hallId'
      fullPath: '/business/dashboard/ticket/$organizationId/halls/$hallId'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdHallsHallIdRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId': {
      id: '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId'
      path: '/seat-maps/$layoutId'
      fullPath: '/business/dashboard/ticket/$organizationId/seat-maps/$layoutId'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdRoute
    }
    '/business/dashboard/ticket/$organizationId/venues/': {
      id: '/business/dashboard/ticket/$organizationId/venues/'
      path: '/'
      fullPath: '/business/dashboard/ticket/$organizationId/venues/'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdVenuesIndexRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdVenuesRoute
    }
    '/business/dashboard/ticket/$organizationId/venues/$venueId': {
      id: '/business/dashboard/ticket/$organizationId/venues/$venueId'
      path: '/$venueId'
      fullPath: '/business/dashboard/ticket/$organizationId/venues/$venueId'
      preLoaderRoute: typeof BusinessDashboardTicketOrganizationIdVenuesVenueIdRouteImport
      parentRoute: typeof BusinessDashboardTicketOrganizationIdVenuesRoute
    }
  }
}

interface BusinessDashboardBranchesRouteChildren {
  BusinessDashboardBranchesBranchIdRoute: typeof BusinessDashboardBranchesBranchIdRoute
  BusinessDashboardBranchesIndexRoute: typeof BusinessDashboardBranchesIndexRoute
}

const BusinessDashboardBranchesRouteChildren: BusinessDashboardBranchesRouteChildren =
  {
    BusinessDashboardBranchesBranchIdRoute:
      BusinessDashboardBranchesBranchIdRoute,
    BusinessDashboardBranchesIndexRoute: BusinessDashboardBranchesIndexRoute,
  }

const BusinessDashboardBranchesRouteWithChildren =
  BusinessDashboardBranchesRoute._addFileChildren(
    BusinessDashboardBranchesRouteChildren,
  )

interface BusinessDashboardEmployeesRouteChildren {
  BusinessDashboardEmployeesEmployeeIdRoute: typeof BusinessDashboardEmployeesEmployeeIdRoute
  BusinessDashboardEmployeesIndexRoute: typeof BusinessDashboardEmployeesIndexRoute
}

const BusinessDashboardEmployeesRouteChildren: BusinessDashboardEmployeesRouteChildren =
  {
    BusinessDashboardEmployeesEmployeeIdRoute:
      BusinessDashboardEmployeesEmployeeIdRoute,
    BusinessDashboardEmployeesIndexRoute: BusinessDashboardEmployeesIndexRoute,
  }

const BusinessDashboardEmployeesRouteWithChildren =
  BusinessDashboardEmployeesRoute._addFileChildren(
    BusinessDashboardEmployeesRouteChildren,
  )

interface BusinessDashboardTicketOrganizationIdEventsRouteChildren {
  BusinessDashboardTicketOrganizationIdEventsEventIdRoute: typeof BusinessDashboardTicketOrganizationIdEventsEventIdRoute
  BusinessDashboardTicketOrganizationIdEventsNewRoute: typeof BusinessDashboardTicketOrganizationIdEventsNewRoute
  BusinessDashboardTicketOrganizationIdEventsIndexRoute: typeof BusinessDashboardTicketOrganizationIdEventsIndexRoute
}

const BusinessDashboardTicketOrganizationIdEventsRouteChildren: BusinessDashboardTicketOrganizationIdEventsRouteChildren =
  {
    BusinessDashboardTicketOrganizationIdEventsEventIdRoute:
      BusinessDashboardTicketOrganizationIdEventsEventIdRoute,
    BusinessDashboardTicketOrganizationIdEventsNewRoute:
      BusinessDashboardTicketOrganizationIdEventsNewRoute,
    BusinessDashboardTicketOrganizationIdEventsIndexRoute:
      BusinessDashboardTicketOrganizationIdEventsIndexRoute,
  }

const BusinessDashboardTicketOrganizationIdEventsRouteWithChildren =
  BusinessDashboardTicketOrganizationIdEventsRoute._addFileChildren(
    BusinessDashboardTicketOrganizationIdEventsRouteChildren,
  )

interface BusinessDashboardTicketOrganizationIdVenuesRouteChildren {
  BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute: typeof BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute
  BusinessDashboardTicketOrganizationIdVenuesIndexRoute: typeof BusinessDashboardTicketOrganizationIdVenuesIndexRoute
}

const BusinessDashboardTicketOrganizationIdVenuesRouteChildren: BusinessDashboardTicketOrganizationIdVenuesRouteChildren =
  {
    BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute:
      BusinessDashboardTicketOrganizationIdVenuesVenueIdRoute,
    BusinessDashboardTicketOrganizationIdVenuesIndexRoute:
      BusinessDashboardTicketOrganizationIdVenuesIndexRoute,
  }

const BusinessDashboardTicketOrganizationIdVenuesRouteWithChildren =
  BusinessDashboardTicketOrganizationIdVenuesRoute._addFileChildren(
    BusinessDashboardTicketOrganizationIdVenuesRouteChildren,
  )

interface BusinessDashboardTicketOrganizationIdRouteChildren {
  BusinessDashboardTicketOrganizationIdDashboardRoute: typeof BusinessDashboardTicketOrganizationIdDashboardRoute
  BusinessDashboardTicketOrganizationIdEventsRoute: typeof BusinessDashboardTicketOrganizationIdEventsRouteWithChildren
  BusinessDashboardTicketOrganizationIdGatesRoute: typeof BusinessDashboardTicketOrganizationIdGatesRoute
  BusinessDashboardTicketOrganizationIdHelpRoute: typeof BusinessDashboardTicketOrganizationIdHelpRoute
  BusinessDashboardTicketOrganizationIdOrdersRoute: typeof BusinessDashboardTicketOrganizationIdOrdersRoute
  BusinessDashboardTicketOrganizationIdReportsRoute: typeof BusinessDashboardTicketOrganizationIdReportsRoute
  BusinessDashboardTicketOrganizationIdScannerRoute: typeof BusinessDashboardTicketOrganizationIdScannerRoute
  BusinessDashboardTicketOrganizationIdSchedulesRoute: typeof BusinessDashboardTicketOrganizationIdSchedulesRoute
  BusinessDashboardTicketOrganizationIdSettingsRoute: typeof BusinessDashboardTicketOrganizationIdSettingsRoute
  BusinessDashboardTicketOrganizationIdTicketTypesRoute: typeof BusinessDashboardTicketOrganizationIdTicketTypesRoute
  BusinessDashboardTicketOrganizationIdVenuesRoute: typeof BusinessDashboardTicketOrganizationIdVenuesRouteWithChildren
  BusinessDashboardTicketOrganizationIdIndexRoute: typeof BusinessDashboardTicketOrganizationIdIndexRoute
  BusinessDashboardTicketOrganizationIdHallsHallIdRoute: typeof BusinessDashboardTicketOrganizationIdHallsHallIdRoute
  BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute: typeof BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute
}

const BusinessDashboardTicketOrganizationIdRouteChildren: BusinessDashboardTicketOrganizationIdRouteChildren =
  {
    BusinessDashboardTicketOrganizationIdDashboardRoute:
      BusinessDashboardTicketOrganizationIdDashboardRoute,
    BusinessDashboardTicketOrganizationIdEventsRoute:
      BusinessDashboardTicketOrganizationIdEventsRouteWithChildren,
    BusinessDashboardTicketOrganizationIdGatesRoute:
      BusinessDashboardTicketOrganizationIdGatesRoute,
    BusinessDashboardTicketOrganizationIdHelpRoute:
      BusinessDashboardTicketOrganizationIdHelpRoute,
    BusinessDashboardTicketOrganizationIdOrdersRoute:
      BusinessDashboardTicketOrganizationIdOrdersRoute,
    BusinessDashboardTicketOrganizationIdReportsRoute:
      BusinessDashboardTicketOrganizationIdReportsRoute,
    BusinessDashboardTicketOrganizationIdScannerRoute:
      BusinessDashboardTicketOrganizationIdScannerRoute,
    BusinessDashboardTicketOrganizationIdSchedulesRoute:
      BusinessDashboardTicketOrganizationIdSchedulesRoute,
    BusinessDashboardTicketOrganizationIdSettingsRoute:
      BusinessDashboardTicketOrganizationIdSettingsRoute,
    BusinessDashboardTicketOrganizationIdTicketTypesRoute:
      BusinessDashboardTicketOrganizationIdTicketTypesRoute,
    BusinessDashboardTicketOrganizationIdVenuesRoute:
      BusinessDashboardTicketOrganizationIdVenuesRouteWithChildren,
    BusinessDashboardTicketOrganizationIdIndexRoute:
      BusinessDashboardTicketOrganizationIdIndexRoute,
    BusinessDashboardTicketOrganizationIdHallsHallIdRoute:
      BusinessDashboardTicketOrganizationIdHallsHallIdRoute,
    BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute:
      BusinessDashboardTicketOrganizationIdSeatMapsLayoutIdRoute,
  }

const BusinessDashboardTicketOrganizationIdRouteWithChildren =
  BusinessDashboardTicketOrganizationIdRoute._addFileChildren(
    BusinessDashboardTicketOrganizationIdRouteChildren,
  )

interface BusinessDashboardRouteChildren {
  BusinessDashboardBillingRoute: typeof BusinessDashboardBillingRoute
  BusinessDashboardBookingsRoute: typeof BusinessDashboardBookingsRoute
  BusinessDashboardBranchesRoute: typeof BusinessDashboardBranchesRouteWithChildren
  BusinessDashboardCalendarRoute: typeof BusinessDashboardCalendarRoute
  BusinessDashboardChatRoute: typeof BusinessDashboardChatRoute
  BusinessDashboardCustomersRoute: typeof BusinessDashboardCustomersRoute
  BusinessDashboardEmployeeScheduleRoute: typeof BusinessDashboardEmployeeScheduleRoute
  BusinessDashboardEmployeesRoute: typeof BusinessDashboardEmployeesRouteWithChildren
  BusinessDashboardFinanceRoute: typeof BusinessDashboardFinanceRoute
  BusinessDashboardNotificationsRoute: typeof BusinessDashboardNotificationsRoute
  BusinessDashboardOrgProfileRoute: typeof BusinessDashboardOrgProfileRoute
  BusinessDashboardPerformanceRoute: typeof BusinessDashboardPerformanceRoute
  BusinessDashboardProfileRoute: typeof BusinessDashboardProfileRoute
  BusinessDashboardQrPromotionRoute: typeof BusinessDashboardQrPromotionRoute
  BusinessDashboardReportsRoute: typeof BusinessDashboardReportsRoute
  BusinessDashboardScheduleRoute: typeof BusinessDashboardScheduleRoute
  BusinessDashboardServicesRoute: typeof BusinessDashboardServicesRoute
  BusinessDashboardSettingsRoute: typeof BusinessDashboardSettingsRoute
  BusinessDashboardTodayClientsRoute: typeof BusinessDashboardTodayClientsRoute
  BusinessDashboardIndexRoute: typeof BusinessDashboardIndexRoute
  BusinessDashboardGovernmentModuleRoute: typeof BusinessDashboardGovernmentModuleRoute
  BusinessDashboardTicketOrganizationIdRoute: typeof BusinessDashboardTicketOrganizationIdRouteWithChildren
}

const BusinessDashboardRouteChildren: BusinessDashboardRouteChildren = {
  BusinessDashboardBillingRoute: BusinessDashboardBillingRoute,
  BusinessDashboardBookingsRoute: BusinessDashboardBookingsRoute,
  BusinessDashboardBranchesRoute: BusinessDashboardBranchesRouteWithChildren,
  BusinessDashboardCalendarRoute: BusinessDashboardCalendarRoute,
  BusinessDashboardChatRoute: BusinessDashboardChatRoute,
  BusinessDashboardCustomersRoute: BusinessDashboardCustomersRoute,
  BusinessDashboardEmployeeScheduleRoute:
    BusinessDashboardEmployeeScheduleRoute,
  BusinessDashboardEmployeesRoute: BusinessDashboardEmployeesRouteWithChildren,
  BusinessDashboardFinanceRoute: BusinessDashboardFinanceRoute,
  BusinessDashboardNotificationsRoute: BusinessDashboardNotificationsRoute,
  BusinessDashboardOrgProfileRoute: BusinessDashboardOrgProfileRoute,
  BusinessDashboardPerformanceRoute: BusinessDashboardPerformanceRoute,
  BusinessDashboardProfileRoute: BusinessDashboardProfileRoute,
  BusinessDashboardQrPromotionRoute: BusinessDashboardQrPromotionRoute,
  BusinessDashboardReportsRoute: BusinessDashboardReportsRoute,
  BusinessDashboardScheduleRoute: BusinessDashboardScheduleRoute,
  BusinessDashboardServicesRoute: BusinessDashboardServicesRoute,
  BusinessDashboardSettingsRoute: BusinessDashboardSettingsRoute,
  BusinessDashboardTodayClientsRoute: BusinessDashboardTodayClientsRoute,
  BusinessDashboardIndexRoute: BusinessDashboardIndexRoute,
  BusinessDashboardGovernmentModuleRoute:
    BusinessDashboardGovernmentModuleRoute,
  BusinessDashboardTicketOrganizationIdRoute:
    BusinessDashboardTicketOrganizationIdRouteWithChildren,
}

const BusinessDashboardRouteWithChildren =
  BusinessDashboardRoute._addFileChildren(BusinessDashboardRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  BusinessChatRoute: BusinessChatRoute,
  BusinessDashboardRoute: BusinessDashboardRouteWithChildren,
  BusinessRegisterRoute: BusinessRegisterRoute,
  EventEventIdRoute: EventEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
