import type {
  GovernmentActivity,
  GovernmentDepartment,
  GovernmentEmployee,
  GovernmentMeeting,
  GovernmentNewsItem,
  GovernmentPetition,
  GovernmentRequest,
  GovernmentTask,
  OfficialDocument,
} from "./types";

function isoDate(offset = 0) {
  const date = new Date();
  date.setDate(date.getDate() + offset);
  return date.toISOString().slice(0, 10);
}

function isoTime(hoursAgo = 0) {
  return new Date(Date.now() - hoursAgo * 3_600_000).toISOString();
}

export const GOVERNMENT_DEPARTMENTS: GovernmentDepartment[] = [
  {
    id: "org",
    name: "Нийслэлийн Цахим хөгжил, мэдээллийн технологийн газар",
    level: "organization",
    employeeCount: 86,
  },
  {
    id: "dep-admin",
    name: "Захиргаа, удирдлагын хэлтэс",
    parentId: "org",
    level: "department",
    headEmployeeId: "ge1",
    employeeCount: 18,
  },
  {
    id: "dep-policy",
    name: "Бодлого, төлөвлөлтийн хэлтэс",
    parentId: "org",
    level: "department",
    headEmployeeId: "ge2",
    employeeCount: 22,
  },
  {
    id: "dep-digital",
    name: "Цахим засаглалын хэлтэс",
    parentId: "org",
    level: "department",
    headEmployeeId: "ge3",
    employeeCount: 27,
  },
  {
    id: "div-records",
    name: "Бичиг хэрэг, архивын тасаг",
    parentId: "dep-admin",
    level: "division",
    headEmployeeId: "ge4",
    employeeCount: 8,
  },
  {
    id: "unit-citizen",
    name: "Иргэдтэй харилцах нэгж",
    parentId: "dep-admin",
    level: "unit",
    headEmployeeId: "ge5",
    employeeCount: 11,
  },
];

export const GOVERNMENT_EMPLOYEES: GovernmentEmployee[] = [
  {
    id: "ge1",
    name: "Б. Энхтөр",
    email: "enkhtur@gov.mn",
    phone: "9901 1201",
    departmentId: "dep-admin",
    position: "Газрын дарга",
    positionClassification: "ТЗ-13",
    permissionPreset: "executive",
    online: true,
    attendanceStatus: "present",
    checkIn: "08:42",
    appointmentDate: "2022-03-14",
  },
  {
    id: "ge2",
    name: "О. Мөнхзул",
    email: "munkhzul@gov.mn",
    phone: "9902 1202",
    departmentId: "dep-policy",
    position: "Хэлтсийн дарга",
    positionClassification: "ТЗ-11",
    permissionPreset: "department-head",
    online: true,
    attendanceStatus: "present",
    checkIn: "08:55",
    appointmentDate: "2023-01-09",
  },
  {
    id: "ge3",
    name: "Д. Тэмүүлэн",
    email: "temuulen@gov.mn",
    phone: "9903 1203",
    departmentId: "dep-digital",
    position: "Хэлтсийн дарга",
    positionClassification: "ТЗ-11",
    permissionPreset: "department-head",
    online: true,
    attendanceStatus: "remote",
    checkIn: "09:03",
    appointmentDate: "2021-08-02",
  },
  {
    id: "ge4",
    name: "Ц. Саруул",
    email: "saruul@gov.mn",
    phone: "9904 1204",
    departmentId: "div-records",
    position: "Ахлах мэргэжилтэн",
    positionClassification: "ТЗ-8",
    permissionPreset: "records-officer",
    online: false,
    attendanceStatus: "away",
    checkIn: "08:51",
    appointmentDate: "2024-02-19",
  },
  {
    id: "ge5",
    name: "Н. Анужин",
    email: "anujin@gov.mn",
    phone: "9905 1205",
    departmentId: "unit-citizen",
    position: "Өргөдөл, гомдол хариуцсан мэргэжилтэн",
    positionClassification: "ТЗ-7",
    permissionPreset: "petition-officer",
    online: true,
    attendanceStatus: "present",
    checkIn: "08:47",
    appointmentDate: "2024-09-16",
  },
  {
    id: "ge6",
    name: "П. Номин",
    email: "nomin@gov.mn",
    phone: "9906 1206",
    departmentId: "dep-admin",
    position: "Хүний нөөцийн мэргэжилтэн",
    positionClassification: "ТЗ-8",
    permissionPreset: "hr-officer",
    online: true,
    attendanceStatus: "present",
    checkIn: "08:59",
    appointmentDate: "2020-11-03",
  },
  {
    id: "ge7",
    name: "Г. Билгүүн",
    email: "bilguun@gov.mn",
    phone: "9907 1207",
    departmentId: "dep-digital",
    position: "Системийн шинжээч",
    positionClassification: "ТЗ-7",
    permissionPreset: "employee",
    online: false,
    attendanceStatus: "offline",
    appointmentDate: "2025-04-07",
  },
];

export const GOVERNMENT_DOCUMENTS: OfficialDocument[] = [
  {
    id: "doc1",
    number: "НЗДТГ/2026-1842",
    title: "Цахим үйлчилгээний нэгдсэн төлөвлөгөө хүргүүлэх тухай",
    sender: "Нийслэлийн Засаг даргын Тамгын газар",
    receivedAt: isoDate(0),
    dueDate: isoDate(5),
    responsibleDepartmentId: "dep-policy",
    status: "received",
    confidentiality: "internal",
  },
  {
    id: "doc2",
    number: "ЦХИХХЯ/03-821",
    title: "Мэдээллийн аюулгүй байдлын үнэлгээ хийх чиглэл",
    sender: "Цахим хөгжил, инновац, харилцаа холбооны яам",
    receivedAt: isoDate(-1),
    dueDate: isoDate(2),
    responsibleDepartmentId: "dep-digital",
    status: "in-review",
    confidentiality: "restricted",
  },
  {
    id: "doc3",
    number: "ДХА/2026-417",
    title: "Архивын баримтын тооллогын дүн",
    sender: "Дотоод хяналт, аудитын хэлтэс",
    receivedAt: isoDate(-3),
    responsibleDepartmentId: "div-records",
    status: "approved",
    confidentiality: "internal",
  },
  {
    id: "doc4",
    number: "ИТХ/07-294",
    title: "Нийслэлийн ИТХ-ын тогтоолын хэрэгжилтийг тайлагнах тухай",
    sender: "Нийслэлийн Иргэдийн Төлөөлөгчдийн Хурал",
    receivedAt: isoDate(-4),
    dueDate: isoDate(-1),
    responsibleDepartmentId: "dep-admin",
    status: "in-review",
    confidentiality: "public",
  },
];

export const GOVERNMENT_TASKS: GovernmentTask[] = [
  {
    id: "gt1",
    title: "2026 оны цахим шилжилтийн төлөвлөгөөг эцэслэх",
    assigneeId: "ge2",
    departmentId: "dep-policy",
    dueDate: isoDate(2),
    priority: "high",
    status: "in-progress",
    progress: 72,
  },
  {
    id: "gt2",
    title: "Албан бичгийн хариу төслийг хянуулах",
    assigneeId: "ge4",
    departmentId: "div-records",
    dueDate: isoDate(0),
    priority: "urgent",
    status: "in-progress",
    progress: 45,
  },
  {
    id: "gt3",
    title: "Иргэдийн өргөдлийн сарын мэдээг нэгтгэх",
    assigneeId: "ge5",
    departmentId: "unit-citizen",
    dueDate: isoDate(4),
    priority: "normal",
    status: "new",
    progress: 0,
  },
  {
    id: "gt4",
    title: "Дотоод системийн нэвтрэх эрхийн аудит",
    assigneeId: "ge7",
    departmentId: "dep-digital",
    dueDate: isoDate(-2),
    priority: "high",
    status: "blocked",
    progress: 60,
  },
  {
    id: "gt5",
    title: "Сургалтын хэрэгцээний судалгааг боловсруулах",
    assigneeId: "ge6",
    departmentId: "dep-admin",
    dueDate: isoDate(7),
    priority: "low",
    status: "completed",
    progress: 100,
  },
];

export const GOVERNMENT_MEETINGS: GovernmentMeeting[] = [
  {
    id: "gm1",
    title: "Удирдлагын шуурхай зөвлөгөөн",
    date: isoDate(0),
    startTime: "10:00",
    endTime: "11:00",
    location: "А хурлын танхим",
    organizer: "Захиргаа, удирдлагын хэлтэс",
    attendeeCount: 14,
    type: "meeting",
  },
  {
    id: "gm2",
    title: "Цахим үйлчилгээний архитектурын хэлэлцүүлэг",
    date: isoDate(0),
    startTime: "14:30",
    endTime: "16:00",
    location: "Teams · Цахим",
    organizer: "Цахим засаглалын хэлтэс",
    attendeeCount: 22,
    type: "meeting",
  },
  {
    id: "gm3",
    title: "Төрийн албан хаагчийн ёс зүйн сургалт",
    date: isoDate(1),
    startTime: "09:30",
    endTime: "12:00",
    location: "Их танхим",
    organizer: "Хүний нөөц",
    attendeeCount: 64,
    type: "training",
  },
];

export const GOVERNMENT_PETITIONS: GovernmentPetition[] = [
  {
    id: "gp1",
    number: "ӨГ-2026-00842",
    subject: "Цахим үйлчилгээний нэвтрэлтийн талаар",
    citizenName: "С. Батболд",
    receivedAt: isoDate(0),
    dueDate: isoDate(14),
    departmentId: "unit-citizen",
    status: "received",
    channel: "web",
  },
  {
    id: "gp2",
    number: "ӨГ-2026-00837",
    subject: "Мэдээлэл шинэчлэх хүсэлт",
    citizenName: "Д. Оюун",
    receivedAt: isoDate(-1),
    dueDate: isoDate(9),
    departmentId: "dep-digital",
    status: "in-review",
    channel: "email",
  },
  {
    id: "gp3",
    number: "ӨГ-2026-00812",
    subject: "Лавлагааны мэдээллийн зөрүү",
    citizenName: "Б. Төгөлдөр",
    receivedAt: isoDate(-6),
    dueDate: isoDate(3),
    departmentId: "unit-citizen",
    status: "resolved",
    channel: "paper",
  },
];

export const GOVERNMENT_ACTIVITIES: GovernmentActivity[] = [
  {
    id: "ga1",
    type: "document-received",
    title: "Шинэ албан бичиг хүлээн авлаа",
    description: "НЗДТГ/2026-1842 дугаартай албан бичиг бүртгэгдэв.",
    actor: "Ц. Саруул",
    at: isoTime(0.2),
    department: "Бичиг хэрэг, архивын тасаг",
  },
  {
    id: "ga2",
    type: "task-assigned",
    title: "Шинэ үүрэг даалгавар оноов",
    description: "2026 оны цахим шилжилтийн төлөвлөгөөг эцэслэх",
    actor: "Б. Энхтөр",
    at: isoTime(0.8),
    department: "Бодлого, төлөвлөлтийн хэлтэс",
  },
  {
    id: "ga3",
    type: "meeting-changed",
    title: "Хурал шинэчлэгдлээ",
    description: "Цахим үйлчилгээний архитектурын хэлэлцүүлэг 14:30 цагт болно.",
    actor: "Д. Тэмүүлэн",
    at: isoTime(1.3),
    department: "Цахим засаглалын хэлтэс",
  },
  {
    id: "ga4",
    type: "attendance",
    title: "Ажилтан ирцээ бүртгүүллээ",
    description: "Н. Анужин 08:47 цагт ирсэн.",
    actor: "Н. Анужин",
    at: isoTime(2.1),
  },
  {
    id: "ga5",
    type: "petition-received",
    title: "Өргөдөл хүлээн авлаа",
    description: "ӨГ-2026-00842 дугаартай өргөдөл цахимаар ирэв.",
    actor: "Иргэдийн цахим систем",
    at: isoTime(3.4),
    department: "Иргэдтэй харилцах нэгж",
  },
  {
    id: "ga6",
    type: "document-decision",
    title: "Албан бичиг батлагдлаа",
    description: "ДХА/2026-417 дугаартай баримтыг удирдлага батлав.",
    actor: "Б. Энхтөр",
    at: isoTime(5.2),
  },
  {
    id: "ga7",
    type: "announcement",
    title: "Дотоод зарлал нийтлэгдлээ",
    description: "Мэдээллийн аюулгүй байдлын дотоод сургалтын хуваарь гарлаа.",
    actor: "Хүний нөөц",
    at: isoTime(7.5),
  },
  {
    id: "ga8",
    type: "petition-resolved",
    title: "Өргөдлийг шийдвэрлэлээ",
    description: "ӨГ-2026-00812 өргөдлийн хариуг иргэнд хүргүүлэв.",
    actor: "Н. Анужин",
    at: isoTime(10),
    department: "Иргэдтэй харилцах нэгж",
  },
];

export const GOVERNMENT_NEWS: GovernmentNewsItem[] = [
  {
    id: "gn1",
    title: "Төрийн үйлчилгээний цахим шилжилтийн 2026 оны зорилтыг танилцууллаа",
    source: "Цахим хөгжил, инновац, харилцаа холбооны яам",
    publishedAt: isoDate(0),
    category: "Засгийн газрын мэдээ",
  },
  {
    id: "gn2",
    title: "Байгууллагын мэдээллийн аюулгүй байдлын шинэ журам батлагдав",
    source: "Дотоод мэдээ",
    publishedAt: isoDate(-1),
    category: "Байгууллагын мэдээ",
  },
  {
    id: "gn3",
    title: "Албан хаагчдын сургалтын нэгдсэн хөтөлбөр эхэлнэ",
    source: "Хүний нөөц",
    publishedAt: isoDate(-2),
    category: "Сургалт",
  },
];

export const GOVERNMENT_REQUESTS: GovernmentRequest[] = [
  {
    id: "gr1",
    type: "Дотоод хүсэлт",
    subtype: "Техникийн дэмжлэг",
    title: "Хурлын танхимын дэлгэц тохируулах",
    departmentId: "dep-digital",
    responsibleEmployeeId: "ge7",
    priority: "normal",
    dueDate: isoDate(1),
    description: "А хурлын танхимын дэлгэцийг шуурхай зөвлөгөөнөөс өмнө шалгах.",
    attachments: [],
    reviewingManagerId: "ge3",
    status: "in-review",
    createdAt: isoTime(26),
    createdBy: "Ц. Саруул",
  },
];
